
package us.co.state.dwr;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ColoradoWaterSMSSoap", targetNamespace = "http://www.dwr.state.co.us/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ColoradoWaterSMSSoap {


    /**
     * Get transmission data for streamflow gages. Data is available as either raw incoming values, or aggregated hourly or daily averages.  Data should be considered provisional in nature and is subject to revision.
     * 
     * @param aggregation
     * @param startDate
     * @param smsStatusHeader
     * @param abbrev
     * @param endDate
     * @param smsDisclaimerHeader
     * @param variable
     * @return
     *     returns us.co.state.dwr.ArrayOfStreamflowTransmission
     */
    @WebMethod(operationName = "GetSMSProvisionalData", action = "http://www.dwr.state.co.us/GetSMSProvisionalData")
    @WebResult(name = "GetSMSProvisionalDataResult", targetNamespace = "http://www.dwr.state.co.us/")
    @RequestWrapper(localName = "GetSMSProvisionalData", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetSMSProvisionalData")
    @ResponseWrapper(localName = "GetSMSProvisionalDataResponse", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetSMSProvisionalDataResponse")
    public ArrayOfStreamflowTransmission getSMSProvisionalData(
        @WebParam(name = "Abbrev", targetNamespace = "http://www.dwr.state.co.us/")
        String abbrev,
        @WebParam(name = "Variable", targetNamespace = "http://www.dwr.state.co.us/")
        String variable,
        @WebParam(name = "StartDate", targetNamespace = "http://www.dwr.state.co.us/")
        String startDate,
        @WebParam(name = "EndDate", targetNamespace = "http://www.dwr.state.co.us/")
        String endDate,
        @WebParam(name = "Aggregation", targetNamespace = "http://www.dwr.state.co.us/")
        String aggregation,
        @WebParam(name = "SmsDisclaimerHeader", targetNamespace = "http://www.dwr.state.co.us/", header = true, mode = WebParam.Mode.OUT, partName = "SmsDisclaimerHeader")
        Holder<SmsDisclaimerHeader> smsDisclaimerHeader,
        @WebParam(name = "SmsStatusHeader", targetNamespace = "http://www.dwr.state.co.us/", header = true, mode = WebParam.Mode.OUT, partName = "SmsStatusHeader")
        Holder<SmsStatusHeader> smsStatusHeader);

    /**
     * Get Current Conditions for Streamflow Gages
     * 
     * @param div
     * @param smsStatusHeader
     * @param abbrev
     * @param smsDisclaimerHeader
     * @param wd
     * @param variable
     * @return
     *     returns us.co.state.dwr.ArrayOfCurrentCondition
     */
    @WebMethod(operationName = "GetSMSCurrentConditions", action = "http://www.dwr.state.co.us/GetSMSCurrentConditions")
    @WebResult(name = "GetSMSCurrentConditionsResult", targetNamespace = "http://www.dwr.state.co.us/")
    @RequestWrapper(localName = "GetSMSCurrentConditions", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetSMSCurrentConditions")
    @ResponseWrapper(localName = "GetSMSCurrentConditionsResponse", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetSMSCurrentConditionsResponse")
    public ArrayOfCurrentCondition getSMSCurrentConditions(
        @WebParam(name = "Div", targetNamespace = "http://www.dwr.state.co.us/")
        int div,
        @WebParam(name = "WD", targetNamespace = "http://www.dwr.state.co.us/")
        int wd,
        @WebParam(name = "Abbrev", targetNamespace = "http://www.dwr.state.co.us/")
        String abbrev,
        @WebParam(name = "Variable", targetNamespace = "http://www.dwr.state.co.us/")
        String variable,
        @WebParam(name = "SmsDisclaimerHeader", targetNamespace = "http://www.dwr.state.co.us/", header = true, mode = WebParam.Mode.OUT, partName = "SmsDisclaimerHeader")
        Holder<SmsDisclaimerHeader> smsDisclaimerHeader,
        @WebParam(name = "SmsStatusHeader", targetNamespace = "http://www.dwr.state.co.us/", header = true, mode = WebParam.Mode.OUT, partName = "SmsStatusHeader")
        Holder<SmsStatusHeader> smsStatusHeader);

    /**
     * Get Streamflow Gaging Stations that are Currently Transmitting
     * 
     * @param div
     * @param smsStatusHeader
     * @param abbrev
     * @param wd
     * @return
     *     returns us.co.state.dwr.ArrayOfStation
     */
    @WebMethod(operationName = "GetSMSTransmittingStations", action = "http://www.dwr.state.co.us/GetSMSTransmittingStations")
    @WebResult(name = "GetSMSTransmittingStationsResult", targetNamespace = "http://www.dwr.state.co.us/")
    @RequestWrapper(localName = "GetSMSTransmittingStations", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetSMSTransmittingStations")
    @ResponseWrapper(localName = "GetSMSTransmittingStationsResponse", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetSMSTransmittingStationsResponse")
    public ArrayOfStation getSMSTransmittingStations(
        @WebParam(name = "Div", targetNamespace = "http://www.dwr.state.co.us/")
        int div,
        @WebParam(name = "WD", targetNamespace = "http://www.dwr.state.co.us/")
        int wd,
        @WebParam(name = "Abbrev", targetNamespace = "http://www.dwr.state.co.us/")
        String abbrev,
        @WebParam(name = "SmsStatusHeader", targetNamespace = "http://www.dwr.state.co.us/", header = true, mode = WebParam.Mode.OUT, partName = "SmsStatusHeader")
        Holder<SmsStatusHeader> smsStatusHeader);

    /**
     * Get Available Variables for a Streamflow Gaging Station (or stations)
     * 
     * @param div
     * @param smsStatusHeader
     * @param abbrev
     * @param wd
     * @return
     *     returns us.co.state.dwr.ArrayOfStationVariables
     */
    @WebMethod(operationName = "GetSMSTransmittingStationVariables", action = "http://www.dwr.state.co.us/GetSMSTransmittingStationVariables")
    @WebResult(name = "GetSMSTransmittingStationVariablesResult", targetNamespace = "http://www.dwr.state.co.us/")
    @RequestWrapper(localName = "GetSMSTransmittingStationVariables", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetSMSTransmittingStationVariables")
    @ResponseWrapper(localName = "GetSMSTransmittingStationVariablesResponse", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetSMSTransmittingStationVariablesResponse")
    public ArrayOfStationVariables getSMSTransmittingStationVariables(
        @WebParam(name = "Div", targetNamespace = "http://www.dwr.state.co.us/")
        int div,
        @WebParam(name = "WD", targetNamespace = "http://www.dwr.state.co.us/")
        int wd,
        @WebParam(name = "Abbrev", targetNamespace = "http://www.dwr.state.co.us/")
        String abbrev,
        @WebParam(name = "SmsStatusHeader", targetNamespace = "http://www.dwr.state.co.us/", header = true, mode = WebParam.Mode.OUT, partName = "SmsStatusHeader")
        Holder<SmsStatusHeader> smsStatusHeader);

    /**
     * Get a Rating Table by the station abbreviation and variable, with all points
     * 
     * @param smsStatusHeader
     * @param abbrev
     * @param smsDisclaimerHeader
     * @param variable
     * @return
     *     returns us.co.state.dwr.RatingTable
     */
    @WebMethod(operationName = "GetSMSCurrentRatingTable", action = "http://www.dwr.state.co.us/GetSMSCurrentRatingTable")
    @WebResult(name = "GetSMSCurrentRatingTableResult", targetNamespace = "http://www.dwr.state.co.us/")
    @RequestWrapper(localName = "GetSMSCurrentRatingTable", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetSMSCurrentRatingTable")
    @ResponseWrapper(localName = "GetSMSCurrentRatingTableResponse", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetSMSCurrentRatingTableResponse")
    public RatingTable getSMSCurrentRatingTable(
        @WebParam(name = "Abbrev", targetNamespace = "http://www.dwr.state.co.us/")
        String abbrev,
        @WebParam(name = "Variable", targetNamespace = "http://www.dwr.state.co.us/")
        String variable,
        @WebParam(name = "SmsDisclaimerHeader", targetNamespace = "http://www.dwr.state.co.us/", header = true, mode = WebParam.Mode.OUT, partName = "SmsDisclaimerHeader")
        Holder<SmsDisclaimerHeader> smsDisclaimerHeader,
        @WebParam(name = "SmsStatusHeader", targetNamespace = "http://www.dwr.state.co.us/", header = true, mode = WebParam.Mode.OUT, partName = "SmsStatusHeader")
        Holder<SmsStatusHeader> smsStatusHeader);

    /**
     * Get a Shift Curve by the station abbreviation and variable, with all points
     * 
     * @param smsStatusHeader
     * @param abbrev
     * @param smsDisclaimerHeader
     * @param variable
     * @return
     *     returns us.co.state.dwr.ShiftCurve
     */
    @WebMethod(operationName = "GetSMSCurrentShiftCurve", action = "http://www.dwr.state.co.us/GetSMSCurrentShiftCurve")
    @WebResult(name = "GetSMSCurrentShiftCurveResult", targetNamespace = "http://www.dwr.state.co.us/")
    @RequestWrapper(localName = "GetSMSCurrentShiftCurve", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetSMSCurrentShiftCurve")
    @ResponseWrapper(localName = "GetSMSCurrentShiftCurveResponse", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetSMSCurrentShiftCurveResponse")
    public ShiftCurve getSMSCurrentShiftCurve(
        @WebParam(name = "Abbrev", targetNamespace = "http://www.dwr.state.co.us/")
        String abbrev,
        @WebParam(name = "Variable", targetNamespace = "http://www.dwr.state.co.us/")
        String variable,
        @WebParam(name = "SmsDisclaimerHeader", targetNamespace = "http://www.dwr.state.co.us/", header = true, mode = WebParam.Mode.OUT, partName = "SmsDisclaimerHeader")
        Holder<SmsDisclaimerHeader> smsDisclaimerHeader,
        @WebParam(name = "SmsStatusHeader", targetNamespace = "http://www.dwr.state.co.us/", header = true, mode = WebParam.Mode.OUT, partName = "SmsStatusHeader")
        Holder<SmsStatusHeader> smsStatusHeader);

    /**
     * Get all water districts
     * 
     * @param smsStatusHeader
     * @return
     *     returns us.co.state.dwr.ArrayOfWaterDistrict
     */
    @WebMethod(operationName = "GetWaterDistricts", action = "http://www.dwr.state.co.us/GetWaterDistricts")
    @WebResult(name = "GetWaterDistrictsResult", targetNamespace = "http://www.dwr.state.co.us/")
    @RequestWrapper(localName = "GetWaterDistricts", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetWaterDistricts")
    @ResponseWrapper(localName = "GetWaterDistrictsResponse", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetWaterDistrictsResponse")
    public ArrayOfWaterDistrict getWaterDistricts(
        @WebParam(name = "SmsStatusHeader", targetNamespace = "http://www.dwr.state.co.us/", header = true, mode = WebParam.Mode.OUT, partName = "SmsStatusHeader")
        Holder<SmsStatusHeader> smsStatusHeader);

    /**
     * Get a list of Error Codes
     * 
     * @return
     *     returns us.co.state.dwr.ErrorCodes
     */
    @WebMethod(operationName = "GetErrorCodes", action = "http://www.dwr.state.co.us/GetErrorCodes")
    @WebResult(name = "GetErrorCodesResult", targetNamespace = "http://www.dwr.state.co.us/")
    @RequestWrapper(localName = "GetErrorCodes", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetErrorCodes")
    @ResponseWrapper(localName = "GetErrorCodesResponse", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetErrorCodesResponse")
    public ErrorCodes getErrorCodes();

    /**
     * Get the description for an Error Code
     * 
     * @param errorCode
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetErrorDescription", action = "http://www.dwr.state.co.us/GetErrorDescription")
    @WebResult(name = "GetErrorDescriptionResult", targetNamespace = "http://www.dwr.state.co.us/")
    @RequestWrapper(localName = "GetErrorDescription", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetErrorDescription")
    @ResponseWrapper(localName = "GetErrorDescriptionResponse", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetErrorDescriptionResponse")
    public String getErrorDescription(
        @WebParam(name = "ErrorCode", targetNamespace = "http://www.dwr.state.co.us/")
        int errorCode);

    /**
     * Get the description for an Error Type
     * 
     * @param errorTypeCode
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetErrorTypeDescription", action = "http://www.dwr.state.co.us/GetErrorTypeDescription")
    @WebResult(name = "GetErrorTypeDescriptionResult", targetNamespace = "http://www.dwr.state.co.us/")
    @RequestWrapper(localName = "GetErrorTypeDescription", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetErrorTypeDescription")
    @ResponseWrapper(localName = "GetErrorTypeDescriptionResponse", targetNamespace = "http://www.dwr.state.co.us/", className = "us.co.state.dwr.GetErrorTypeDescriptionResponse")
    public String getErrorTypeDescription(
        @WebParam(name = "ErrorTypeCode", targetNamespace = "http://www.dwr.state.co.us/")
        int errorTypeCode);

}
